"""Analytics modules."""

from .correlations import (
    CorrelationAnalysisBundle,
    FeatureEngineeringOpportunity,
    PairCorrelationResult,
    TargetCorrelationAnalysis,
    build_candidate_signals_from_correlations,
    discover_feature_engineering_opportunities,
    run_correlation_analysis,
)
from .quality_checks import QualityCheckResult, run_quality_checks
from .expert_priors import ExpertPriorProfile, KnowledgeSource, infer_expert_priors
from .sensor_diagnostics import (
    SensorDiagnostic,
    SensorDiagnosticsSummary,
    run_sensor_diagnostics,
)
from .experiment_design import (
    ExperimentRecommendation,
    recommend_data_trajectories,
    recommendations_to_dict,
)
from .model_recommendation import (
    ModelStrategySummary,
    ProbeModelScore,
    TargetModelRecommendation,
    recommend_model_strategies,
)
from .ranking import (
    CandidateSignal,
    ForcedModelingDirective,
    RankedSignal,
    build_forced_directive,
    rank_surrogate_candidates,
)
from .reporting import (
    build_agent1_report_payload,
    save_agent1_artifacts,
    save_agent1_markdown_report,
)
from .stationarity import StationaritySignalResult, StationaritySummary, assess_stationarity
from .task_detection import (
    CLASSIFICATION_TASK_TYPES,
    SUPPORTED_TASK_TYPES,
    TaskProfile,
    assess_task_profile,
    assess_task_profiles,
    is_classification_task,
    normalize_task_type_hint,
)
from .task_contracts import (
    BENCHMARK_MODE_REPORT_SCHEMA_VERSION,
    BENCHMARK_VS_DEPLOY_REPORT_SCHEMA_VERSION,
    DATASET_SEMANTICS_AUDIT_SCHEMA_VERSION,
    DEPLOYMENT_READINESS_REPORT_SCHEMA_VERSION,
    METRIC_CONTRACT_SCHEMA_VERSION,
    TARGET_SEMANTICS_REPORT_SCHEMA_VERSION,
    TASK_CONTRACT_FILENAMES,
    TASK_PROFILE_CONTRACT_SCHEMA_VERSION,
    build_task_contract_artifacts,
    infer_benchmark_expected,
    read_task_contract_artifacts,
    sync_task_contract_artifacts,
)
from .architecture_routing import (
    ARCHITECTURE_ABLATION_REPORT_SCHEMA_VERSION,
    ARCHITECTURE_FIT_REPORT_SCHEMA_VERSION,
    ARCHITECTURE_REGISTRY_SCHEMA_VERSION,
    ARCHITECTURE_ROUTER_REPORT_SCHEMA_VERSION,
    ARCHITECTURE_ROUTING_FILENAMES,
    CANDIDATE_FAMILY_MATRIX_SCHEMA_VERSION,
    FAMILY_CAPABILITY_MATRIX_SCHEMA_VERSION,
    build_architecture_routing_artifacts,
    default_architecture_candidate_order,
    read_architecture_routing_artifacts,
    sync_architecture_routing_artifacts,
)

__all__ = [
    "CandidateSignal",
    "CorrelationAnalysisBundle",
    "FeatureEngineeringOpportunity",
    "ForcedModelingDirective",
    "ModelStrategySummary",
    "PairCorrelationResult",
    "ProbeModelScore",
    "QualityCheckResult",
    "ExpertPriorProfile",
    "KnowledgeSource",
    "SensorDiagnostic",
    "SensorDiagnosticsSummary",
    "ExperimentRecommendation",
    "RankedSignal",
    "StationaritySignalResult",
    "StationaritySummary",
    "TargetCorrelationAnalysis",
    "assess_stationarity",
    "build_agent1_report_payload",
    "build_candidate_signals_from_correlations",
    "build_forced_directive",
    "discover_feature_engineering_opportunities",
    "rank_surrogate_candidates",
    "run_correlation_analysis",
    "run_quality_checks",
    "infer_expert_priors",
    "run_sensor_diagnostics",
    "recommend_data_trajectories",
    "recommendations_to_dict",
    "save_agent1_artifacts",
    "save_agent1_markdown_report",
    "TargetModelRecommendation",
    "TaskProfile",
    "TASK_CONTRACT_FILENAMES",
    "TASK_PROFILE_CONTRACT_SCHEMA_VERSION",
    "TARGET_SEMANTICS_REPORT_SCHEMA_VERSION",
    "METRIC_CONTRACT_SCHEMA_VERSION",
    "BENCHMARK_MODE_REPORT_SCHEMA_VERSION",
    "DEPLOYMENT_READINESS_REPORT_SCHEMA_VERSION",
    "BENCHMARK_VS_DEPLOY_REPORT_SCHEMA_VERSION",
    "DATASET_SEMANTICS_AUDIT_SCHEMA_VERSION",
    "recommend_model_strategies",
    "SUPPORTED_TASK_TYPES",
    "CLASSIFICATION_TASK_TYPES",
    "ARCHITECTURE_ROUTING_FILENAMES",
    "ARCHITECTURE_REGISTRY_SCHEMA_VERSION",
    "ARCHITECTURE_ROUTER_REPORT_SCHEMA_VERSION",
    "CANDIDATE_FAMILY_MATRIX_SCHEMA_VERSION",
    "ARCHITECTURE_FIT_REPORT_SCHEMA_VERSION",
    "FAMILY_CAPABILITY_MATRIX_SCHEMA_VERSION",
    "ARCHITECTURE_ABLATION_REPORT_SCHEMA_VERSION",
    "assess_task_profile",
    "assess_task_profiles",
    "build_architecture_routing_artifacts",
    "build_task_contract_artifacts",
    "default_architecture_candidate_order",
    "infer_benchmark_expected",
    "is_classification_task",
    "normalize_task_type_hint",
    "read_architecture_routing_artifacts",
    "read_task_contract_artifacts",
    "sync_architecture_routing_artifacts",
    "sync_task_contract_artifacts",
]
