"""Slice 14A remote supervision package."""

from .agents import (
    RemoteControlRunResult,
    RemoteDecisionResult,
    apply_remote_approval_decision,
    apply_remote_supervision_handoff,
    render_remote_control_markdown,
    run_remote_control_review,
)
from .models import (
    APPROVAL_DECISION_LOG_SCHEMA_VERSION,
    APPROVAL_REQUEST_QUEUE_SCHEMA_VERSION,
    NOTIFICATION_DELIVERY_REPORT_SCHEMA_VERSION,
    REMOTE_CONTROL_AUDIT_SCHEMA_VERSION,
    REMOTE_CONTROL_CONTROLS_SCHEMA_VERSION,
    REMOTE_OPERATOR_PRESENCE_SCHEMA_VERSION,
    REMOTE_SESSION_MANIFEST_SCHEMA_VERSION,
    REMOTE_TRANSPORT_REPORT_SCHEMA_VERSION,
    SUPERVISION_HANDOFF_SCHEMA_VERSION,
    ApprovalRequestQueueArtifact,
    NotificationDeliveryReportArtifact,
    RemoteControlBundle,
    RemoteControlControls,
    RemoteControlTrace,
    RemoteControlAuditArtifact,
    RemoteOperatorPresenceArtifact,
    RemoteSessionManifestArtifact,
    RemoteTransportReportArtifact,
    SupervisionHandoffArtifact,
    build_remote_control_controls_from_policy,
)
from .storage import (
    APPROVAL_DECISION_LOG_FILENAME,
    REMOTE_CONTROL_FILENAMES,
    append_approval_decision_log,
    read_approval_decision_log,
    read_remote_control_bundle,
    write_remote_control_artifact,
    write_remote_control_bundle,
)

__all__ = [
    "APPROVAL_DECISION_LOG_FILENAME",
    "APPROVAL_DECISION_LOG_SCHEMA_VERSION",
    "APPROVAL_REQUEST_QUEUE_SCHEMA_VERSION",
    "NOTIFICATION_DELIVERY_REPORT_SCHEMA_VERSION",
    "REMOTE_CONTROL_AUDIT_SCHEMA_VERSION",
    "REMOTE_CONTROL_CONTROLS_SCHEMA_VERSION",
    "REMOTE_CONTROL_FILENAMES",
    "REMOTE_OPERATOR_PRESENCE_SCHEMA_VERSION",
    "REMOTE_SESSION_MANIFEST_SCHEMA_VERSION",
    "REMOTE_TRANSPORT_REPORT_SCHEMA_VERSION",
    "SUPERVISION_HANDOFF_SCHEMA_VERSION",
    "ApprovalRequestQueueArtifact",
    "NotificationDeliveryReportArtifact",
    "RemoteControlBundle",
    "RemoteControlControls",
    "RemoteControlRunResult",
    "RemoteControlTrace",
    "RemoteControlAuditArtifact",
    "RemoteDecisionResult",
    "RemoteOperatorPresenceArtifact",
    "RemoteSessionManifestArtifact",
    "RemoteTransportReportArtifact",
    "SupervisionHandoffArtifact",
    "append_approval_decision_log",
    "apply_remote_approval_decision",
    "apply_remote_supervision_handoff",
    "build_remote_control_controls_from_policy",
    "read_approval_decision_log",
    "read_remote_control_bundle",
    "render_remote_control_markdown",
    "run_remote_control_review",
    "write_remote_control_artifact",
    "write_remote_control_bundle",
]
